# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sine_wave/sine_wave.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sine_wave || ORIG_REF_NAME==sine_wave}]
