
function sin_cos_module_config(this_block)

  % Revision History:
  %
  %   25-Nov-2015  (17:57 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\mtech\poonam_vlsi\vlsi_proj\sinn\sin_cos_module.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('sin_cos_module');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('phase_in');
  this_block.addSimulinkInport('clk');

  this_block.addSimulinkOutport('x_out');
  this_block.addSimulinkOutport('y_out');

  x_out_port = this_block.port('x_out');
  x_out_port.setType('UFix_10_0');
  y_out_port = this_block.port('y_out');
  y_out_port.setType('UFix_10_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('phase_in').width ~= 10);
      this_block.setError('Input data type for port "phase_in" must have width=10.');
    end

    if (this_block.port('clk').width ~= 1);
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('sin_cos_module.vhd');

return;


