# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/modulation_vhdl/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/modulation_vhdl/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/modulation_vhdl/test_qpskk.vhd
catch { write_hwdef -file test_qpskk.hwdef }
synth_design -top test_qpskk -part xc7vx485tffg1157-1
write_checkpoint -noxdef test_qpskk.dcp
catch { report_utilization -file test_qpskk_utilization_synth.rpt -pb test_qpskk_utilization_synth.pb }
