# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/project_5/project_5.cache/wt [current_project]
set_property parent.project_path C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/sin_cos_module.vhd
  C:/Users/mtech/poonam_vlsi/vlsi_proj/sinn/one.vhd
}
catch { write_hwdef -file one.hwdef }
synth_design -top one -part xc7vx485tffg1157-1
write_checkpoint -noxdef one.dcp
catch { report_utilization -file one_utilization_synth.rpt -pb one_utilization_synth.pb }
